export const types = {
  SET_ELEMENTSDATA: 'SET_ELEMENTSDATA',
  SET_ELEMENTSDATA_LOADSTATE: 'SET_ELEMENTSDATA_LOADSTATE',
  ADD_MESSAGE: 'ADD_MESSAGE',
  SET_SELECTEDDREAM: 'SET_SELECTEDDREAM',
  SET_SELECTEDDREAM_LOADSTATE: 'SET_SELECTEDDREAM_LOADSTATE',
  SET_POSTDREAM_LOADSTATE: 'SET_POSTDREAM_LOADSTATE',
  SET_POSTPURCHASE_LOADSTATE: 'SET_POSTPURCHASE_LOADSTATE',
};
